### ISSUE TITLE
Gradle errors when building app from source

### ISSUE THREAD

**Issue by christianfl** [nfdz/saved.io-plus-plus#1]
Hi! I don't have Google play services and your app is not on F-Droid so I tried to build it from source. I used Android Studio 2.3.2 on Linux Ubuntu 17.04 and imported the app via Gradle.

Gradle Sync tells:

> Error:Failed to resolve: annotationProcessor
> Error:(34, 13) Failed to resolve: com.android.support.constraint:constraint-layout:1.0.2

Gradle build tells:

> Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
> Could not find com.android.support.constraint:constraint-layout:1.0.2.
> Required by:
> project :app

As I'm not an expert I couldn't see the mistake. Thanks in advance.

**Comment by christianfl** [comment]
Fixed it. I just had to go to: File > Settings > Appearance & Behavior > System Settings > Android SDK > SDK Tools and added the _ConstraintLayout_ under Support Repository.
The build was successful and the app is working for me now.

**Comment by nfdz** [comment]
Hi, I'm glad to hear that there's no problem. I had uploaded the binary when creating the release. I just added an icon on the main page to ease to visitors this option.

**Comment by christianfl** [comment]
Oh, I didn't have the idea to look over there. Thanks for that, it will be much easier for people like me in the future.
